stages:
  data_collection:
    cmd: python src/data/data_collection.py
    deps:
    - src/data/data_collection.py
    outs:
    - data/raw

  data_processed:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/processed

  model_training:
    cmd: python src/models/train.py
    deps:
    - data/processed
    - src/models/train.py
    outs:
    - model.pkl


  model_evaluation:
    cmd: python src/models/evaluation.py
    deps:
    - model.pkl
    - src/models/evaluation.py
    metrics:
    - metrics.json
