name: CI Pipeline

on:
  push:
    branches:
      - main # It's good practice to specify which branches trigger the CI

jobs: 
  project_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # Indentation for 'uses' must align with 'name' and 'run'
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with: # A colon ':' is required after 'with'
          python-version: '3.12' # Using '3.12' is safer than a specific patch version like '3.12.9'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc

      - name: Run DVC Pipeline
        env: 
          DAGS_HUB_SECRET: ${{secrets.DAGS_HUB_SECRET}}
        # DVC repro requires the DVC cache to be pulled first
        run: |
          # 2. Run the DVC pipeline
          dvc repro